"""Korean labels for the proton quantitative workflow."""
KO = {
    "Import H NMR ASCII...": "H NMR ASCII 가져오기...",
    "Open H NMR library...": "H NMR 라이브러리 열기...",
    "Parameter library...": "파라미터 라이브러리...",
    "Preprocessing...": "전처리...",
    "Quantitative analysis...": "정량 분석...",
    "Phase override...": "위상 직접 지정...",
    "Calculation details...": "계산 과정 확인...",
    "Export processed CSV...": "처리 데이터 CSV 저장...",
    "Rename...": "이름 변경...",
    "Edit...": "편집...",
    "Add...": "추가...",
    "Save complete calculation record...": "전체 계산 기록 저장...",
    "Export library JSON...": "라이브러리 JSON 저장...",
    "Import library JSON...": "라이브러리 JSON 가져오기...",
    "Export parameters...": "파라미터 내보내기...",
    "Import parameters...": "파라미터 가져오기...",
    "H NMR parameter library": "H NMR 파라미터 라이브러리",
    "H NMR spectrum library": "H NMR 스펙트럼 라이브러리",
    "H NMR common preprocessing": "H NMR 공통 전처리",
    "Confirm H NMR quantitative analysis": "H NMR 정량 분석 조건 확인",
    "H NMR calculation details": "H NMR 계산 과정",
    "Loaded H NMR spectra": "불러온 H NMR 스펙트럼",
    "Saved H NMR spectra": "저장된 H NMR 스펙트럼",
    "Active": "활성",
    "Prep.": "전처리",
    "Group": "그룹",
    "Phase correction": "위상 보정",
    "Baseline correction": "베이스라인 보정",
    "Imaginary": "허수부",
    "Core / excess / fit": "코어 / 초과 신호 / 피팅",
    "Quantitative results": "정량 분석 결과",
    "Result / units": "결과 / 단위",
    "Value": "값",
    "Internal standards": "내부 표준",
    "Core capacities": "코어 최대 용량",
    "Ligands": "리간드",
    "Sample masses": "시료 질량",
    "Get preprocessing condition": "공통 전처리 조건 가져오기",
    "Apply common preprocessing": "공통 전처리 적용",
    "Clear selection": "선택 해제",
    "Automatic zero-order phase correction": "자동 0차 위상 보정",
    "Robust linear edge baseline correction": "양 끝 구간의 강건 선형 베이스라인 보정",
    "Baseline edge fraction (each end)": "베이스라인에 사용할 각 끝 구간 비율",
    "Additional zero-order phase (degrees)": "추가 0차 위상 (도)",
    "First-order phase across range (degrees)": "전체 구간의 1차 위상 (도)",
    "Shared Gaussian FWHM (ppm; 0 = none)": "공통 Gaussian FWHM (ppm; 0 = 없음)",
    "Align to first activated spectrum": "첫 활성 스펙트럼 기준 정렬",
    "Maximum shift (ppm)": "최대 이동 (ppm)",
    "Alignment ppm minimum": "정렬 구간 최소 ppm",
    "Alignment ppm maximum": "정렬 구간 최대 ppm",
    "Core": "코어",
    "Ligand / hypothetical ligand for blank check": "리간드 / 미변형 검증용 가상 리간드",
    "Mass used as coverage denominator (mg)": "coverage 분모에 사용할 질량 (mg)",
    "Pristine reference mass (mg)": "미변형 기준 시료 질량 (mg)",
    "Core maximum loading (umol/mg)": "코어 최대 로딩 (umol/mg)",
    "Parent ligand MW (g/mol)": "원래 리간드 분자량 (g/mol)",
    "Effective H represented by quantified band": "정량 밴드에 해당하는 유효 H 수",
    "Core scaling method": "코어 스케일링 방법",
    "Use saved common preprocessing": "저장된 공통 전처리 사용",
    "Pristine core reference": "미변형 코어 기준 스펙트럼",
    "Parameter presets": "파라미터 프리셋",
    "Sample and core": "시료와 코어",
    "Calibration": "검량 조건",
    "Regions and decomposition": "영역과 분해",
    "Confirm parameters and calculate": "파라미터 확인 후 계산",
    "Internal standard area": "내부 표준 면적",
    "Internal standard amount (mmol H)": "내부 표준 H 양 (mmol H)",
    "Standard area basis": "표준 면적 단위",
    "STANDARD original grid step (ppm)": "표준 데이터 원래 grid 간격 (ppm)",
    "Frequency (MHz, for Hz area)": "주파수 (MHz; Hz 면적 변환용)",
    "Sample response multiplier to standard scale": "시료 신호를 표준 배율로 환산하는 계수",
    "Core response multiplier to standard scale": "코어 신호를 표준 배율로 환산하는 계수",
    "Standard area unit and scale verified": "표준 면적 단위 및 배율 확인",
    "Quantitative acquisition / response verified": "정량 측정 조건 및 응답 확인",
    "Aliphatic minimum (ppm)": "Aliphatic 최소 (ppm)",
    "Aliphatic maximum (ppm)": "Aliphatic 최대 (ppm)",
    "Aromatic minimum (ppm)": "Aromatic 최소 (ppm)",
    "Aromatic maximum (ppm)": "Aromatic 최대 (ppm)",
    "Area method: regions / three-band Gaussian": "면적 계산: 영역 적분 / 3-band Gaussian",
    "Band capture / effective proton count verified": "밴드 포괄 범위 및 유효 H 수 확인",
}
