"""Korean labels for the proton quantitative workflow."""
KO = {
    'Model / calibration notes': '모델 / 보정계수 설명',
    'Additional ligand G fraction (0=L, 1=G; blank=fit)': '추가 리간드 G 비율 (0=L, 1=G; 빈칸=피팅)',
    'Aromatic G fraction (Ver1 only)': 'Aromatic G 비율 (Ver1 전용)',
    'Decomposition model': '분해 모델 (기본: model Ver1)',
    'Ver2 pristine core reference': 'Ver2 미변형 core 기준 스펙트럼',
    'Ver2 ligand center lower bound (ppm)': 'Ver2 추가 리간드 중심 하한 (ppm)',
    'Ver2 ligand center upper bound (ppm)': 'Ver2 추가 리간드 중심 상한 (ppm)',
    'Ver2 ligand minimum FWHM (ppm)': 'Ver2 추가 리간드 최소 FWHM (ppm)',
    'Ver2 ligand maximum FWHM (ppm)': 'Ver2 추가 리간드 최대 FWHM (ppm)',
    'Ver2 maximum core shift (ppm; 0 = fixed)': 'Ver2 core 최대 이동 (ppm; 0 = 고정)',
    'Ver2 maximum extra core FWHM (ppm; 0 = none)': 'Ver2 core 추가 선폭 상한 (ppm; 0 = 없음)',
    'Michael scenario includes one linkage N-H (if captured)': 'Michael 경계: 결합부 N–H 1개 포함 가정 (적분에 포함될 때)',
    'Schiff H override (blank = automatic)': 'Schiff 경계의 H 수 직접 지정 (빈칸 = 자동)',
    'Michael H override (blank = automatic)': 'Michael 경계의 H 수 직접 지정 (빈칸 = 자동)',
    'Measured core template': '실측 core 기준 성분',
    'Additional ligand component': '추가 리간드 성분',
    'Coverage range % (H-count scenarios)': 'Coverage 범위 % (H 수 가정)',
    'Calculate all (provisional)...': '전체 잠정 coverage 계산...',
    'All H NMR provisional results': '전체 H NMR 잠정 정량 결과',
    'Confirm and calculate all': '확인 후 전체 계산',
    'Export provisional results CSV...': '잠정 결과 CSV 저장...',
    'Show provisional coverage despite unresolved checks': '미확인 항목이 있어도 잠정 coverage 표시',
    'Refine phase using resolved sidebands': '검출된 위성피크를 고려한 위상 보정',
    'Refine phase / baseline': '위상 / 기저선 재보정',
    'Coverage % (provisional)': 'Coverage % (잠정)',
    'Response S / R': '응답 배율 S / R',
    'Std. basis': '표준 면적 단위',
    'Mass mg': '질량 mg',
    '400 MHz / 20 kHz preset': '400 MHz / 20 kHz 설정',
    'MAS preset (Hz; both 0 = estimated spacing)': 'MAS 설정 (Hz; 둘 다 0이면 간격 추정)',
    '1H frequency preset (MHz)': '1H 관측 주파수 설정 (MHz)',
    'Aliphatic G fraction (0=L, 1=G; blank=fit)': 'Aliphatic G 비율 (0=L, 1=G; 빈칸=피팅)',
    'Aromatic G fraction (0=L, 1=G; blank=fit)': 'Aromatic G 비율 (0=L, 1=G; 빈칸=피팅)',
    'Signed satellite heights (diagnostic only)': 'Satellite 음수 높이 허용 (진단용)',
    'Component integrals...': '성분별 적분표...',
    'H NMR component integrals': 'H NMR 성분별 적분표',
    'Phase sensitivity...': '위상 민감도 검증...',
    'H NMR phase sensitivity': 'H NMR 위상 민감도 검증',
    'Run phase sensitivity': '위상 민감도 계산',
    'Export sensitivity record...': '민감도 검증 기록 저장...',
    "Import H NMR ASCII...": "H NMR ASCII 가져오기...",
    "Import NMR ASCII (C / H auto-detect)": "NMR ASCII 가져오기 (C / H 자동 구분)",
    "NMR ASCII import": "NMR ASCII 가져오기",
    "Open H NMR library...": "H NMR 라이브러리 열기...",
    "Parameter library...": "파라미터 라이브러리...",
    "Preprocessing...": "전처리...",
    "Quantitative analysis...": "정량 분석...",
    "Phase override...": "위상 직접 지정...",
    "Calculation details...": "계산 과정 확인...",
    "Export processed CSV...": "처리 데이터 CSV 저장...",
    "Rename...": "이름 변경...",
    "Edit...": "편집...",
    "Add...": "추가...",
    "Save complete calculation record...": "전체 계산 기록 저장...",
    "Export library JSON...": "라이브러리 JSON 저장...",
    "Import library JSON...": "라이브러리 JSON 가져오기...",
    "Export parameters...": "파라미터 내보내기...",
    "Import parameters...": "파라미터 가져오기...",
    "H NMR parameter library": "H NMR 파라미터 라이브러리",
    "H NMR spectrum library": "H NMR 스펙트럼 라이브러리",
    "H NMR common preprocessing": "H NMR 공통 전처리",
    "Confirm H NMR quantitative analysis": "H NMR 정량 분석 조건 확인",
    "H NMR calculation details": "H NMR 계산 과정",
    "Loaded H NMR spectra": "불러온 H NMR 스펙트럼",
    "Saved H NMR spectra": "저장된 H NMR 스펙트럼",
    "Active": "활성",
    "Prep.": "전처리",
    "Group": "그룹",
    "Phase correction": "위상 보정",
    "Baseline correction": "베이스라인 보정",
    "Imaginary": "허수부",
    "Core / excess / fit": "코어 / 초과 신호 / 피팅",
    "Quantitative results": "정량 분석 결과",
    "Result / units": "결과 / 단위",
    "Value": "값",
    "Internal standards": "내부 표준",
    "Core capacities": "코어 최대 용량",
    "Ligands": "리간드",
    "Sample masses": "시료 질량",
    "Get preprocessing condition": "공통 전처리 조건 가져오기",
    "Apply common preprocessing": "공통 전처리 적용",
    "Clear selection": "선택 해제",
    "Automatic zero-order phase correction": "자동 0차 위상 보정",
    "Robust linear edge baseline correction": "양 끝 구간의 강건 선형 베이스라인 보정",
    "Baseline edge fraction (each end)": "베이스라인에 사용할 각 끝 구간 비율",
    "Additional zero-order phase (degrees)": "추가 0차 위상 (도)",
    "First-order phase across range (degrees)": "전체 구간의 1차 위상 (도)",
    "Shared Gaussian FWHM (ppm; 0 = none)": "공통 Gaussian FWHM (ppm; 0 = 없음)",
    "Align to first activated spectrum": "첫 활성 스펙트럼 기준 정렬",
    "Maximum shift (ppm)": "최대 이동 (ppm)",
    "Alignment ppm minimum": "정렬 구간 최소 ppm",
    "Alignment ppm maximum": "정렬 구간 최대 ppm",
    "Core": "코어",
    "Ligand / hypothetical ligand for blank check": "리간드 / 미변형 검증용 가상 리간드",
    "Mass used as coverage denominator (mg)": "coverage 분모에 사용할 질량 (mg)",
    "Pristine reference mass (mg)": "미변형 기준 시료 질량 (mg)",
    "Core maximum loading (umol/mg)": "코어 최대 로딩 (umol/mg)",
    "Parent ligand MW (g/mol)": "원래 리간드 분자량 (g/mol)",
    "Effective H represented by quantified band": "정량 밴드에 해당하는 유효 H 수",
    "Core scaling method": "코어 스케일링 방법",
    "Use saved common preprocessing": "저장된 공통 전처리 사용",
    "Pristine core reference": "미변형 코어 기준 스펙트럼",
    "Parameter presets": "파라미터 프리셋",
    "Sample and core": "시료와 코어",
    "Calibration": "검량 조건",
    "Regions and decomposition": "영역과 분해",
    "Confirm parameters and calculate": "파라미터 확인 후 계산",
    "Internal standard area": "내부 표준 면적",
    "Internal standard amount (umol H)": "내부 표준 H 양 (μmol H)",
    "Coverage calculation method": "Coverage 계산 방식",
    "Known core mass in sample (mg; mass method only)": "시료 내 core 질량 (mg; mass 방식에서만 사용)",
    "Copy value": "값 복사",
    "Copy results table": "결과표 복사",
    "Model sensitivity...": "모델 민감도 검증...",
    "H NMR model sensitivity": "H NMR 모델 민감도 검증",
    "Run model comparison": "모델 비교 실행",
    "Copy comparison": "비교표 복사",
    "Save review...": "검증 기록 저장...",
    "Standard area basis": "표준 면적 단위",
    "STANDARD original grid step (ppm)": "표준 데이터 원래 grid 간격 (ppm)",
    "Frequency (MHz, for Hz area)": "주파수 (MHz; Hz 면적 변환용)",
    "Sample response multiplier to standard scale": "시료 신호를 표준 배율로 환산하는 계수",
    "Core response multiplier to standard scale": "코어 신호를 표준 배율로 환산하는 계수",
    "Standard area unit and scale verified": "표준 면적 단위 및 배율 확인",
    "Quantitative acquisition / response verified": "정량 측정 조건 및 응답 확인",
    "Aliphatic minimum (ppm)": "Aliphatic 최소 (ppm)",
    "Aliphatic maximum (ppm)": "Aliphatic 최대 (ppm)",
    "Aromatic minimum (ppm)": "Aromatic 최소 (ppm)",
    "Aromatic maximum (ppm)": "Aromatic 최대 (ppm)",
    "Area method: regions / three-band Gaussian": "면적 계산: 영역 적분 / 3-band Gaussian",
    "Band capture / effective proton count verified": "밴드 포괄 범위 및 유효 H 수 확인",
    "Decompose spectrum...": "스펙트럼 분해...",
    "H NMR decomposition": "H NMR 성분 분해",
    "Show decomposition": "분해 성분 표시",
    "Fit and preview": "피팅 및 미리보기",
    "Apply decomposition to spectrum": "스펙트럼에 분해 적용",
    "Fit / component integration minimum (ppm)": "피팅 / 성분 적분 최소 (ppm)",
    "Fit / component integration maximum (ppm)": "피팅 / 성분 적분 최대 (ppm)",
    "Aliphatic center lower bound (ppm)": "Aliphatic 피크 중심 하한 (ppm)",
    "Aliphatic center upper bound (ppm)": "Aliphatic 피크 중심 상한 (ppm)",
    "Aromatic center lower bound (ppm)": "Aromatic 피크 중심 하한 (ppm)",
    "Aromatic center upper bound (ppm)": "Aromatic 피크 중심 상한 (ppm)",
    "Minimum component FWHM (ppm)": "성분 FWHM 최소 (ppm)",
    "Maximum component FWHM (ppm)": "성분 FWHM 최대 (ppm)",
    "Component line shape": "성분 선 모양 모델",
    "Add unassigned overlap band between center ranges": "중심 범위 사이에 미배정 중첩 성분 추가",
    "H atoms represented per ligand (not particle mass)": "리간드당 해당 H 수 (입자 질량 추정 아님)",
    "H atoms represented per ligand (blank allowed)": "리간드당 해당 H 수 (빈칸 허용)",
    "Known core mass in sample (mg; blank = total mass approximation)": "시료 내 알려진 core 질량 (mg; 빈칸=전체 질량 근사)",
    "Component assignments, H count and core model reviewed": "성분 배정·H 수·core 모델 검토 완료",
    "Shade fitted component areas": "분해 성분 면적 음영 표시",
}
