"""Lab DLS workspace translations."""
from .lab_dls import STATISTICS_NOTE, AVERAGING_NOTE

KO = {
    "Hide": "숨김",
    "Exclude": "분석 제외",
    "[excluded]": "[제외됨]",
    "Average (n={n})": "평균 (n={n})",
    "Mean R labels": "mean R 표시",
    "Mean lines": "평균 수직선",
    "Average distribution only": "평균 분포만 표시",
    "Averages use included measurements. Hide only affects individual curves.": "평균은 분석에 포함한 측정만 사용합니다. 숨김은 개별 곡선 표시에만 적용됩니다.",
    "Particle averages; expand + for individual measurements.": "입자별 평균입니다. +를 누르면 개별 측정이 펼쳐집니다.",
    "No visible measurements. Check Hide / Exclude.": "표시할 측정이 없습니다. 숨김·분석 제외 설정을 확인하세요.",
    "Click the legend to edit it. Drag inside to move, or a corner to resize. Click outside or press Esc to finish.": "범례를 클릭해 편집을 켜세요. 안쪽을 드래그하면 이동하고 모서리를 드래그하면 크기가 바뀝니다. 바깥을 클릭하거나 Esc를 누르면 편집이 끝납니다.",
    "Radius": "반지름",
    "Lab DLS library": "Lab DLS 라이브러리",
    "Import Lab DLS CSV…": "Lab DLS CSV 가져오기…",
    "Open Lab DLS library…": "Lab DLS 라이브러리 열기…",
    "Loaded particles": "불러온 입자",
    "Particle name": "입자 이름",
    "Selected particle": "선택한 입자",
    "Particle overlay": "입자 그래프 오버레이",
    "Distribution results": "분포 계산 결과",
    "Mean R (nm)": "평균 반지름 (nm)",
    "Mean D (nm)": "평균 직경 (nm)",
    "%PD (distribution)": "%PD (분포 기준)",
    "Measurement": "측정",
    "Measurement average (n={n})": "측정 평균 (n={n})",
    "Representative curve": "대표 평균 곡선",
    "CSV intensity-weighted distribution; all exported bins.": "CSV intensity 가중 분포 · 전체 데이터 기준",
    "Register graph overlay": "그래프 오버레이 등록",
    "Show all measurements in overlay": "오버레이에 모든 측정 표시",
    "Registered overlay particles": "오버레이 등록 입자",
    "Remove from overlay": "오버레이에서 해제",
    "Imported {n} particles.": "입자 {n}개를 가져왔습니다.",
    "Saved {n} particles to Lab DLS library.": "Lab DLS 라이브러리에 입자 {n}개를 저장했습니다.",
    "Lab DLS import": "Lab DLS 가져오기",
    "Delete saved particles? The current data list is kept.": "저장한 입자를 삭제할까요? 현재 데이터 목록은 유지됩니다.",
    "Fit Y axis": "Y축 자동 맞춤",
    "Calculation method…": "계산 방식…",
    "Calculation method": "계산 방식",
    "Export results…": "결과 내보내기…",
    "Register particles with the overlay button.": "오버레이 등록 버튼으로 입자를 추가하세요.",
    "Import a CSV and select a particle.": "CSV를 가져와 입자를 선택하세요.",
    "Peaks exceed the Y range. Use Fit Y axis to see the full curves.": "피크가 Y축 범위를 넘습니다. Y축 자동 맞춤으로 전체 곡선을 확인하세요.",
    "Lab DLS annotations": "Lab DLS 주석",
    "Show mean-radius lines": "평균 반지름 위치에 수직선 표시",
    "Show mean R labels": "mean R 주석 표시",
    "Logarithmic radius axis": "반지름 축 로그 스케일",
    "Bold mean R labels": "mean R 주석 굵게",
    "Mean line style": "평균 수직선 모양",
    "Mean line width": "평균 수직선 굵기",
    "Mean R font size": "mean R 글자 크기",
    "Mean R font family": "mean R 글꼴",
    "Annotation opacity (0–1)": "주석 불투명도 (0–1)",
    "Decimal places": "소수점 자릿수",
    "Annotation color (blank = curve)": "주석 색상 (빈칸 = 곡선 색)",
    "Reset mean R label positions": "mean R 주석 위치 초기화",
    "Drag mean R labels directly on the plot. Copy graph includes the visible labels.": "그래프의 mean R 주석을 직접 드래그하세요. 그래프 복사에도 현재 주석이 포함됩니다.",
    "Enter valid colors, line width 0–20, font size 4–72, opacity 0–1 and decimals 0–8.": "유효한 색상, 선 굵기 0 초과~20, 글자 크기 4~72, 불투명도 0~1, 자릿수 0~8을 입력하세요.",
    "Lab DLS uses Radius (nm), Meas 1, Meas 2, ... CSV exports.": "Lab DLS는 Radius (nm), Meas 1, Meas 2, ... 형식의 CSV를 읽습니다.",
    "Save Lab DLS library JSON": "Lab DLS 라이브러리 JSON 저장",
    "Load Lab DLS library JSON": "Lab DLS 라이브러리 JSON 불러오기",
    "Label positions (graph fractions)": "주석 위치 (그래프 비율 좌표)",
    "Label X": "주석 X 위치",
    "Label Y": "주석 Y 위치",
    "Mean R labels can be dragged in the desktop edition; use X/Y positions here.": "데스크톱에서는 mean R 주석을 드래그할 수 있습니다. 웹에서는 X/Y 위치를 입력하세요.",
    STATISTICS_NOTE: "CSV 분포 계산: 평균 R = Σ(I×R)/ΣI, 평균 D = 2×평균 R, %PD = 100×√[Σ(I×(R-평균 R)²)/ΣI]/평균 R입니다. 화면 축 범위와 관계없이 모든 원본 bin을 계산에 사용합니다. 측정 평균은 분석에 포함한 측정 결과의 산술평균입니다. 숨김은 개별 곡선 표시에만 적용하고, 분석 제외는 모든 평균 계산에서 제외합니다. 장비의 cumulants Z-average 또는 PDI 값과는 다릅니다.",
    AVERAGING_NOTE: "대표 곡선: 분석에 포함한 측정을 공통의 균일한 log(radius) 좌표에 선형 보간한 뒤 동일 가중치로 평균합니다. smoothing, fitting, 피크 정규화는 하지 않습니다. 끝부분이 0인 분포만 바깥을 0으로 확장합니다. 대표 곡선의 mean R은 해당 곡선에서 계산하며, 개별 측정 결과의 평균은 별도로 표시합니다.",
}
