"""Shared Korean labels for the desktop and web ssNMR workspace."""
KO = {
    'Custom region': 'Custom 구간',
    'Custom min': 'Custom 최솟값',
    'Custom max': 'Custom 최댓값',
    'Reprocess region': '구간별 재전처리',
    'Processing range': '전처리 범위',
    'Region statistics use separate preprocessing. Integral ratios use one shared preprocessing result for both regions.': '구간별 통계는 각 구간에서 재전처리합니다. 적분비는 두 구간에 공통으로 적용한 전처리 결과를 사용합니다.',
    'View region': '표시 구간',
    'The selected region needs increasing numeric bounds and at least three common measured points.': '선택한 구간의 최솟값과 최댓값을 숫자로 입력하고, 최솟값을 더 작게 설정하세요. 두 스펙트럼의 공통 측정점이 최소 3개 필요합니다.',
    'Comparison range': '전체 비교 구간',
    'Aliphatic region': 'Aliphatic 구간',
    'Aromatic region': 'Aromatic 구간',
    'Updating results…': '결과 갱신 중…',
    'Import ASCII TXT…': 'ASCII TXT 가져오기…',
    'Import selected files': '선택 파일 가져오기',
    'Import TopSpin ASCII TXT data': 'TopSpin ASCII TXT 데이터를 가져오세요',
    'Remove from list': '목록에서 제거',
    'Rename…': '이름 변경…',
    'Save to library': '라이브러리에 저장',
    'Saved to library.': '라이브러리에 저장했습니다.',
    'Open ssNMR library…': 'ssNMR 라이브러리 열기…',
    'ssNMR library': 'ssNMR 라이브러리',
    'Loaded spectra': '불러온 스펙트럼',
    'Saved spectra': '저장된 스펙트럼',
    'Saved spectra: {count}': '저장된 스펙트럼: {count}개',
    'Column 4 = ppm; column 2 = intensity. Click a row to preview its raw spectrum.': '4열 = ppm, 2열 = intensity. 항목을 클릭하면 원본 스펙트럼을 표시합니다.',
    'Compare two spectra…': '두 스펙트럼 비교…',
    'Spectrum comparison': '스펙트럼 비교',
    'Select two spectra': '두 스펙트럼 선택',
    'Load at least two spectra.': '스펙트럼을 두 개 이상 불러오세요.',
    'Choose two different spectra.': '서로 다른 스펙트럼을 선택하세요.',
    'Reference A': '기준 스펙트럼 A',
    'Spectrum B': '비교 스펙트럼 B',
    'reference': '기준',
    'Continue to preprocessing': '전처리로 이동',
    'ssNMR preprocessing': 'ssNMR 전처리',
    'Common ppm minimum': '공통 ppm 최솟값',
    'Common ppm maximum': '공통 ppm 최댓값',
    'Grid step (ppm)': '격자 간격 (ppm)',
    'Baseline edge fraction': '베이스라인 양끝 비율',
    'Maximum B shift (ppm)': 'B 최대 이동량 (ppm)',
    'Alignment minimum (blank = full)': '정렬 구간 최솟값 (빈칸 = 전체)',
    'Alignment maximum (blank = full)': '정렬 구간 최댓값 (빈칸 = 전체)',
    'Shared Gaussian FWHM (ppm)': '동일 Gaussian FWHM (ppm)',
    'Automatic linear edge baseline': '양끝 선형 베이스라인 자동 보정',
    'Automatic bounded chemical-shift alignment': '제한 범위 내 chemical-shift 자동 정렬',
    'Normalization': '정규화',
    'Maximum absolute intensity': '최대 절대 intensity',
    'Total absolute area': '전체 절대 면적',
    'None': '없음',
    'Real-only ASCII: preserve exported TopSpin phase; complex phase correction is unavailable.': '실수 intensity만 포함된 ASCII: TopSpin에서 내보낸 위상을 유지합니다. 복소 위상 보정은 수행할 수 없습니다.',
    'The union range is used by default. Missing coverage stays blank; calculations use measured overlap. Gaussian smoothing uses the same ppm width for both spectra. Normalization uses the full common measured range.': '기본 범위는 두 스펙트럼의 합집합입니다. 측정값이 없는 구간은 비워 두며, 계산에는 겹치는 측정 구간만 사용합니다. 두 스펙트럼에 동일한 ppm 폭의 Gaussian 처리를 적용하고, 전체 공통 측정 범위로 정규화합니다.',
    'Processing…': '처리 중…',
    'Process and compare': '전처리 후 비교',
    'Preprocessing settings…': '전처리 설정…',
    'Export comparison CSV…': '비교 데이터 CSV 저장…',
    'Applied B shift': '적용한 B 이동량',
    'Grid': '격자',
    'Alignment reached the shift limit; inspect the overlay.': '정렬 이동량이 제한값에 도달했습니다. 오버레이를 확인하세요.',
    'Comparison results': '비교 계산 결과',
    'Comparison min': '비교 구간 최솟값',
    'Comparison max': '비교 구간 최댓값',
    'Aliphatic min': 'Aliphatic 최솟값',
    'Aliphatic max': 'Aliphatic 최댓값',
    'Aromatic min': 'Aromatic 최솟값',
    'Aromatic max': 'Aromatic 최댓값',
    'Calculate / update range': '계산 / 범위 적용',
    'R² / r² calculation details…': 'R² / r² 계산 검증…',
    'R² / r² calculation details': 'R² / r² 계산 검증',
    'Integral calculation details…': '적분비 계산 검증…',
    'Integral calculation details': '적분비 계산 검증',
    'R²: direct agreement with reference A (no fitted scaling). r²: squared Pearson r. Integrals use processed signed intensities and exact region boundaries.': 'R²는 기준 A와의 직접 일치도(회귀 적합 없음), r²는 Pearson r의 제곱입니다. 적분은 부호를 보존한 처리 intensity와 정확한 구간 경계를 사용합니다.',
    'Settings changed — click Calculate / update range.': '설정이 변경되었습니다. 계산 / 범위 적용을 누르세요.',
    'Undefined': '계산 불가',
    'Used ppm': '실제 계산 ppm',
    'Ratio': '적분비',
    'Calculate valid results first.': '유효한 결과를 먼저 계산하세요.',
    'Calculation details': '계산 세부 내역',
    'Preprocessing audit': '전처리 검증 내역',
    'Save complete audit…': '전체 검증 내역 저장…',
    'Load into data list': '데이터 목록에 불러오기',
    'Delete from library…': '라이브러리에서 삭제…',
    'Delete selected saved spectra? The current data list is kept.': '선택한 저장 스펙트럼을 삭제할까요? 현재 데이터 목록은 유지됩니다.',
    'Move up': '위로',
    'Move down': '아래로',
    'Web libraries stay in this session. Download the library JSON and import it next time to keep your saved spectra.': '웹 라이브러리는 현재 세션에서 유지됩니다. JSON을 내려받아 다음에 다시 가져오면 저장 데이터를 계속 사용할 수 있습니다.',
    'Download library JSON': '라이브러리 JSON 다운로드',
    'Import library JSON': '라이브러리 JSON 가져오기',
    'Import saved library': '저장 라이브러리 불러오기',
    'No saved spectra.': '저장된 스펙트럼이 없습니다.',
    'Confirm deletion from library': '라이브러리 삭제 확인',
    'Comparison minimum must be less than maximum.': '비교 구간의 최솟값은 최댓값보다 작아야 합니다.',
}
