"""Korean NTA controls; exported instrument flags remain verbatim."""
KO = {
    'Import NTA ZIP…':'NTA ZIP 가져오기…',
    'Import one or more complete NTA ZIP packs.':'완전한 NTA ZIP pack을 하나 이상 가져오세요.',
    'Expected videos per pack':'Pack당 예상 video 수',
    'Samples (Ctrl/Shift for overlay)':'샘플 (Ctrl/Shift로 중첩 선택)',
    'Sample':'샘플', 'Samples':'샘플 목록', 'Videos':'Video 수',
    'Sample name':'샘플 이름', 'Sample / video':'샘플 / video',
    'Select all':'전체 선택', 'NTA plot':'NTA 그래프',
    'Plot type':'그래프 종류', 'Weighting':'가중 방식',
    'Distribution scale':'분포 표시 방식', 'Summary metric':'요약 지표',
    'Error bars / band':'오차막대 / 음영',
    'Show individual video curves':'개별 video 곡선 표시',
    'Included tracks only':'포함된 track만 사용',
    'Use stock concentration':'원액 농도 사용',
    'Histogram / hexbin bins':'히스토그램 / hexbin 구간 수',
    'Point size':'점 크기', 'Point / track opacity':'점 / track 불투명도',
    'Video scope':'Video 선택', 'All included videos':'포함된 모든 video',
    'Maximum displayed tracks':'표시할 최대 track 수',
    'MSD maximum lag (frames)':'MSD 최대 lag (프레임)',
    'Apply NTA controls':'NTA 설정 적용',
    'Stock / surface-area inputs':'원액 / 표면적 계산 입력값',
    'Total dilution factor':'총 희석배수', 'Stock mass (mg/mL)':'원액 질량 농도 (mg/mL)',
    'Ligand footprint (nm²)':'리간드 점유 면적 (nm²)',
    'Apply inputs to selected samples':'선택한 샘플에 입력값 적용',
    'Diluent is a note, not an applied dilution. Blank means unconfirmed.':'Diluent는 메모입니다. 보정 배수는 직접 입력하며, 공란은 미확인입니다.',
    'Methods / interpretation…':'계산 방법 / 해석…',
    'Import details / warnings…':'가져오기 상세 / 확인 사항…',
    'Toggle selected videos':'선택 video 포함 / 제외',
    'Export summary CSV…':'요약 CSV 저장…',
    'Export plot data CSV…':'그래프 데이터 CSV 저장…',
    'Export QC / settings CSV…':'QC / 측정 설정 CSV 저장…',
    'Valid tracks':'유효 track 수', 'Concentration QC':'농도 QC',
    'NTA ZIP packs':'NTA ZIP pack', 'NTA import':'NTA 가져오기',
    'NTA settings':'NTA 설정', 'NTA export':'NTA 저장',
    'Expected video count must be a positive integer.':'예상 video 수는 양의 정수여야 합니다.',
    'Validating NTA packs…':'NTA pack 검증 중…',
    'Imported {n} NTA packs. All required files validated.':'NTA pack {n}개를 가져왔습니다. 필수 파일 검증을 완료했습니다.',
    'Import blocked. Existing data was kept.':'가져오기를 중단했습니다. 기존 데이터는 유지됩니다.',
    'NTA import blocked':'NTA 가져오기 중단',
    'No new data loaded. Fix the listed missing or invalid content and import again.':'새 데이터는 추가하지 않았습니다. 아래의 누락 / 오류를 수정한 뒤 다시 가져오세요.',
    'NTA calculation methods':'NTA 계산 방법', 'NTA import details':'NTA 가져오기 상세',
    'Select a sample.':'샘플을 선택하세요.',
    'Size distribution':'크기 분포', 'Diffusion distribution':'확산계수 분포',
    'Percentile curve':'누적 백분위 곡선', 'Replicate summary':'반복 측정 요약',
    'Run sequence':'측정 순서별 변화', 'Coefficient of variation':'변동계수 (CV)',
    'QC flags':'기기 QC 판정', 'Size–intensity scatter':'크기–강도 산점도',
    'Size–intensity hexbin':'크기–강도 hexbin',
    'Particle size histogram':'개별 track 크기 히스토그램',
    'Track length histogram':'Track 길이 히스토그램',
    'Included / excluded':'포함 / 제외 track',
    'Reported X/Y drift':'기기 보고 X/Y drift',
    'Framewise X/Y drift':'프레임별 X/Y drift',
    'XY trajectories':'XY 궤적', 'Track displacement':'Track 변위',
    'Mean squared displacement':'평균 제곱 변위 (MSD)',
    'Track straightness':'Track 직진도', 'Track intensity':'Track 강도 변화',
    'Validate and import':'검증 후 가져오기',
    'All required files validated.':'모든 필수 파일 검증을 완료했습니다.',
    'Particle / trajectory settings':'입자 / 궤적 설정',
    'Excluded videos':'제외할 video', 'Apply inputs':'입력값 적용',
    'QC / measurement settings':'QC / 측정 설정',
}
