"""Shared desktop/web graph-control translations."""
KO = {
    'Curve colors': '곡선별 색상',
    '+ {count} more · see Curve colors': '+ {count}개 더 · 곡선별 색상에서 확인',
    'Particle color defaults': '입자별 기본 색상',
    'Default': '기본값',
    'Restore default curve colors': '기본 곡선 색상 복원',
    'Choose a color for each curve. Related labels and bands follow the curve color.': '각 곡선의 색상을 선택하세요. 연결된 라벨과 음영도 곡선 색상을 따릅니다.',
    'Plot data to edit its curve colors.': '데이터를 그래프에 표시하면 곡선별 색상을 변경할 수 있습니다.',
    'Enter a valid color, for example #C00000, or use Choose….': '#C00000처럼 올바른 색상을 입력하거나 선택 버튼을 사용하세요.',
    'Graph ratio': '그래프 비율',
    'Fix graph width : height': '그래프 가로 : 세로 비율 고정',
    'Width': '가로',
    'Height': '세로',
    'Square (1:1)': '정사각형 (1:1)',
    'Restore default ratio': '기본 비율 복원',
    'The ratio includes axis labels and applies to preview, clipboard, PNG, SVG and PDF. The default fits the available window. Width/height: 0.1–10.': '축 제목을 포함한 전체 그래프의 비율입니다. 미리보기, 클립보드 복사, PNG·SVG·PDF 저장에 적용됩니다. 기본값은 창 크기에 맞춥니다. 가로/세로: 0.1–10.',
    'The ratio includes axis labels and is preserved in preview and image downloads.': '축 제목을 포함한 전체 그래프 비율이며 미리보기와 이미지 다운로드에 동일하게 적용됩니다.',
    'Graph width and height must be positive; width/height must be between 0.1 and 10.': '가로와 세로는 양수여야 하며, 가로/세로는 0.1~10 사이여야 합니다.',
}
